//! Lock-recovery chokepoint gate: outside `src/sync_util.rs`, in a **non-test**
//! region, no file may privately re-define a lock-recovery helper, nor hand-inline
//! its body, without being named in a register.
//!
//! # Why this gate exists (measured, not supposed)
//!
//! This is repair **#3** of one named class with **no grader between any of them**:
//!
//! * Day 58 — `lock_or_recover` extracted (Mutex).
//! * Day 109 — `rw_read_or_recover` / `rw_write_or_recover` extracted (RwLock), with
//!   a module doc claiming it deduplicated copies in `watch`, `commands_fork`,
//!   `commands_stash` and `commands_todo`. It converted **1 of the 4 files it named**.
//! * Day 193 (#900) — the remaining **6** byte-identical private copies deleted from
//!   `commands_fork.rs`, `commands_stash.rs` and `commands_todo.rs`.
//!
//! So a false authoritative claim sat in the shared module's own doc comment for
//! **84 days**, and blind round 94 found it only by reading the files. My stopping
//! rule fires at N>=3 repairs with no grader between them: the diff must become an
//! **instrument**, not a fourth fix.
//!
//! # The self-concealing property, which is the whole argument for a gate
//!
//! A private copy shares the shared module's **exact** names, so `grep lock_or_recover`
//! counts a *definition* as a *use* of the shared helper. That is precisely how Day
//! 109's claim survived 84 days while being false, and why round 94's own first-pass
//! census reported 69 helper call sites before resolving imports. **No name-based
//! search can catch this.** Only a scan that asks *"is this a definition or a call?"*
//! can — which is what this gate does.
//!
//! # The rule
//!
//! Outside [`CHOKEPOINT_FILE`], in a non-test region, neither of these may appear
//! unregistered:
//!
//! * **A definition** — `fn lock_or_recover`, `fn rw_read_or_recover`,
//!   `fn rw_write_or_recover`. The class that actually bit.
//! * **A hand-inlined body** — `unwrap_or_else(` and `into_inner()` on one line.
//!   Round 94 counted 5 of these; #900 named them as out of scope, so they ship as
//!   registered debt.
//!
//! Two branches, running in **opposite directions**: an unregistered occurrence is
//! fatal (with both remedies printed verbatim), and a registered entry that no longer
//! occurs is *also* fatal — the ratchet, since an exception list only pays itself down
//! if improving is a failure too.
//!
//! # Deliberately NOT using the shared brace scanner
//!
//! `tests/common/mod.rs` holds a brace scanner (#835). This gate deliberately does
//! **not** consume it: a line scan plus test-region truncation is sufficient here and
//! much smaller, which is the same decision `tests/git_chokepoint.rs` records. Do not
//! "fix" this by wiring in the scanner.

use std::io::Write;
use std::path::Path;

/// The one file that *is* the chokepoint, and is exempt by definition.
const CHOKEPOINT_FILE: &str = "src/sync_util.rs";

/// Hand-inlined lock-recovery bodies outside the chokepoint that are deliberately
/// left un-converted, each with the reason a human wrote.
///
/// **This register was generated by running the scan and pasting what it found** —
/// never curated. Its size *is* the finding: round 94's census counted 5 hand-inlined
/// sites (`tool_wrappers.rs` x4, `tools.rs` x1) and this scan independently returns
/// the same 5.
///
/// It is **debt, not absolution**: an entry does not make a copy acceptable, it
/// records by hand that one exists and that I knew. The ratchet is what stops it
/// becoming permission. It can only shrink.
const REGISTERED_INLINE_BODIES: &[(&str, &str, &str)] = &[
    (
        "src/tool_wrappers.rs",
        "already_offered_file_persistence",
        "Hand-inlined `OFFERED.lock().unwrap_or_else(|e| e.into_inner())`. #900 named the \
         5 inlined bodies as out of scope: same lesson as the deleted definitions, but a \
         different remedy (rewrite the expression, not delete a fn), so converting them \
         inside the dedup task would have made the register's size stop being a measurement.",
    ),
    (
        "src/tool_wrappers.rs",
        "record_failure",
        "Hand-inlined `self.counts.lock().unwrap_or_else(|e| e.into_inner())` in \
         ToolFailureTracker. Convertible to `crate::sync_util::lock_or_recover(&self.counts)` \
         with no behaviour change; left as registered debt by #900's stated scope.",
    ),
    (
        "src/tool_wrappers.rs",
        "record_success",
        "Hand-inlined `self.counts.lock().unwrap_or_else(|e| e.into_inner())` in \
         ToolFailureTracker, the sibling of record_failure. Same remedy, same scope decision.",
    ),
    (
        "src/tool_wrappers.rs",
        "get",
        "Hand-inlined `self.counts.lock().unwrap_or_else(|e| e.into_inner())` in \
         ToolFailureTracker. Note the generic fn name: limit 4 below means this one entry \
         would silently cover a second inlined body added anywhere inside a `get` in this file.",
    ),
    (
        "src/tools.rs",
        "already_offered_persistence",
        "Hand-inlined `OFFERED.lock().unwrap_or_else(|e| e.into_inner())`, the near-twin of \
         tool_wrappers.rs::already_offered_file_persistence — two copies of one idea in two \
         files, which is the duplication this gate exists to stop growing.",
    ),
];

/// What kind of lock-recovery occurrence this is. The two are **never folded**: a
/// definition is the 84-day defect, an inlined body is a different remedy, and the
/// message a reader gets has to say which one they hit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum OccurrenceKind {
    /// `fn lock_or_recover` / `fn rw_read_or_recover` / `fn rw_write_or_recover`.
    Definition,
    /// `unwrap_or_else(` and `into_inner()` on one line.
    InlinedBody,
}

/// One lock-recovery occurrence in a file's non-test region.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Occurrence {
    path: String,
    line: usize,
    /// The enclosing `fn` name, used only to make the remedy message pasteable.
    context: String,
    kind: OccurrenceKind,
}

/// A way this gate can be violated. Three values, running in **opposite directions**.
#[derive(Debug, PartialEq, Eq)]
enum LockViolation {
    /// An unregistered occurrence outside the chokepoint. The defect this gate is for.
    Unregistered { occ: Occurrence },
    /// A registered entry that no longer occurs, or whose file has vanished. The ratchet.
    RegisteredDebtPaid { path: String, context: String },
    /// A register entry whose reason is empty or whitespace-only. An unnamed debt
    /// wearing a name is not a name.
    EmptyReason { path: String, context: String },
}

impl LockViolation {
    fn message(&self) -> String {
        match self {
            LockViolation::Unregistered { occ } => {
                let what = match occ.kind {
                    OccurrenceKind::Definition => {
                        "privately DEFINES a lock-recovery helper. A private copy shares \
                         sync_util's exact names, so `grep` counts it as a USE of the shared \
                         helper — this is how a false claim in sync_util's own module doc \
                         survived 84 days (#900)"
                    }
                    OccurrenceKind::InlinedBody => {
                        "hand-inlines a lock-recovery body (`unwrap_or_else(...)` + \
                         `into_inner()`), so it does not route through the chokepoint"
                    }
                };
                format!(
                    "{}:{} ({}) {}.\n     \
                     Fix (either one): route it through \
                     crate::sync_util::{{lock_or_recover, rw_read_or_recover, \
                     rw_write_or_recover}} — #900's conversion needed ZERO call-site edits, \
                     because the names are identical — or, if it genuinely cannot, add\n       \
                     (\"{}\", \"{}\", \"<why this cannot route through sync_util>\"),\n     \
                     to REGISTERED_INLINE_BODIES in tests/lock_recovery_chokepoint.rs.\n     \
                     The gate does not forbid a private copy. It forbids an unnamed one.",
                    occ.path, occ.line, occ.context, what, occ.path, occ.context
                )
            }
            LockViolation::RegisteredDebtPaid { path, context } => format!(
                "REGISTERED_INLINE_BODIES names (\"{path}\", \"{context}\", ...) but no such \
                 occurrence exists any more (converted, or the file/fn is gone).\n     \
                 The debt is paid — delete that line from tests/lock_recovery_chokepoint.rs.\n     \
                 An exception list only pays itself down if IMPROVING is a failure too."
            ),
            LockViolation::EmptyReason { path, context } => format!(
                "REGISTERED_INLINE_BODIES entry (\"{path}\", \"{context}\", ...) has an empty \
                 or whitespace-only reason.\n     \
                 The reason is the only part of the entry a human can act on — an unnamed debt \
                 wearing a name is not a name. Write why this cannot route through sync_util."
            ),
        }
    }
}

/// The decision half: pure, so both fatal branches are proven against **fabricated**
/// inputs rather than by planting a real copy in `src/` (the discipline
/// `tests/orphan_modules.rs` and `tests/feature_gated_tests.rs` both use).
fn classify(occurrences: &[Occurrence], register: &[(&str, &str, &str)]) -> Vec<LockViolation> {
    let mut out = Vec::new();

    for (path, context, reason) in register {
        if reason.trim().is_empty() {
            out.push(LockViolation::EmptyReason {
                path: (*path).to_string(),
                context: (*context).to_string(),
            });
        }
    }

    for occ in occurrences {
        if occ.path == CHOKEPOINT_FILE {
            continue;
        }
        let named = register
            .iter()
            .any(|(p, c, _)| *p == occ.path && *c == occ.context);
        if !named {
            out.push(LockViolation::Unregistered { occ: occ.clone() });
        }
    }

    // The ratchet, running the opposite way.
    for (path, context, _) in register {
        let still_there = occurrences
            .iter()
            .any(|o| o.path == *path && o.context == *context);
        if !still_there {
            out.push(LockViolation::RegisteredDebtPaid {
                path: (*path).to_string(),
                context: (*context).to_string(),
            });
        }
    }

    out
}

/// Where a file's module-level test region starts, if any.
///
/// Keyed on a `#[cfg(test)]` attribute line **followed by a column-0 `mod`** — never a
/// bare `#[cfg(test)]`. `src/git.rs` carries item-level `#[cfg(test)]` attributes **at
/// column 0** at lines 8, 44 and 77, followed by `const` and `fn`, with its real test
/// module far below; a bare split would blank that file's entire production half.
fn test_region_start(lines: &[&str]) -> Option<usize> {
    let attr = format!("#[cfg{}]", "(test)");
    for (i, line) in lines.iter().enumerate() {
        if line.trim() != attr {
            continue;
        }
        for next in lines.iter().skip(i + 1) {
            if next.trim().is_empty() {
                continue;
            }
            if next.starts_with("mod ") || next.starts_with("pub mod ") {
                return Some(i);
            }
            break;
        }
    }
    None
}

/// The three helper names, assembled at runtime so this gate cannot match its own source.
fn helper_names() -> Vec<String> {
    vec![
        format!("{}_or_recover", "lock"),
        format!("rw_{}_or_recover", "read"),
        format!("rw_{}_or_recover", "write"),
    ]
}

/// Does this line DEFINE a helper (rather than call one)? The whole discriminator.
fn defines_helper(line: &str, names: &[String]) -> bool {
    let Some(idx) = line.find("fn ") else {
        return false;
    };
    let after = line[idx + 3..].trim_start();
    names.iter().any(|n| {
        after.strip_prefix(n.as_str()).is_some_and(|rest| {
            !rest
                .chars()
                .next()
                .is_some_and(|c| c.is_alphanumeric() || c == '_')
        })
    })
}

/// Does this line hand-inline a recovery body? Matched **by shape, not by a fixed
/// closure parameter name**, so a copy writing `|poisoned|` or `|err|` is still seen.
fn inlines_recovery_body(line: &str) -> bool {
    line.contains(&format!("unwrap_or_{}(", "else"))
        && line.contains(&format!("into_{}()", "inner"))
}

fn scan_file(path: &str, source: &str, names: &[String]) -> Vec<Occurrence> {
    let lines: Vec<&str> = source.lines().collect();
    let end = test_region_start(&lines).unwrap_or(lines.len());
    let mut out = Vec::new();
    let mut current_fn = String::from("(top level)");
    for (i, line) in lines[..end].iter().enumerate() {
        if let Some(idx) = line.find("fn ") {
            let after = &line[idx + 3..];
            let name: String = after
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                current_fn = name;
            }
        }
        let kind = if defines_helper(line, names) {
            Some(OccurrenceKind::Definition)
        } else if inlines_recovery_body(line) {
            Some(OccurrenceKind::InlinedBody)
        } else {
            None
        };
        if let Some(kind) = kind {
            out.push(Occurrence {
                path: path.to_string(),
                line: i + 1,
                context: current_fn.clone(),
                kind,
            });
        }
    }
    out
}

/// All filesystem walking lives here, at the single call site.
fn collect_occurrences() -> (Vec<Occurrence>, usize) {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let names = helper_names();
    let mut out = Vec::new();
    let mut files = 0usize;
    let mut stack = vec![root.join("src")];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().is_some_and(|e| e == "rs") {
                let Ok(src) = std::fs::read_to_string(&p) else {
                    continue;
                };
                files += 1;
                let rel = p
                    .strip_prefix(root)
                    .unwrap_or(&p)
                    .to_string_lossy()
                    .replace('\\', "/");
                out.extend(scan_file(&rel, &src, &names));
            }
        }
    }
    (out, files)
}

/// Printed on **every passing run** through a raw stderr handle — never `eprintln!`,
/// because libtest's capture hook discards macro output from *passing* tests, which is
/// exactly what a clean run produces. "Could not check" must never read as
/// "checked; clean".
fn write_limits(occurrences: &[Occurrence], files: usize) {
    let defs = occurrences
        .iter()
        .filter(|o| o.kind == OccurrenceKind::Definition)
        .count();
    let inlined_outside = occurrences
        .iter()
        .filter(|o| o.kind == OccurrenceKind::InlinedBody && o.path != CHOKEPOINT_FILE)
        .count();
    let mut err = std::io::stderr();
    let _ = write!(
        err,
        "\n[lock-recovery chokepoint] census (Day 193, 2026-09-09): \
         {files} file(s) scanned under src/ | {defs} helper definition(s), \
         all at the {CHOKEPOINT_FILE} chokepoint | {inlined_outside} hand-inlined \
         body/bodies outside it, named by {} register entry/entries.\n\
         LIMITS (so \"could not check\" cannot read as \"checked; clean\"):\n\
         1. TEXT match, not a parser — a copy that renames the function, splits the body \
            across lines, or restructures it is invisible to this gate.\n\
         2. The 13 skip-on-poison sites (`if let Ok(..) = m.lock()`, `.lock().ok()`) are \
            deliberately OUT OF SCOPE and are NOT bypasses: they are a different POLICY \
            (skip the work rather than recover it), so converting them would be a \
            behaviour change dressed as a dedup.\n\
         3. It says nothing about whether routing is CORRECT — only that an unnamed \
            duplicate does not exist. Presence is mechanically checkable; correctness is not.\n\
         4. The register key is (path, fn), NOT (path, line), so ONE entry covers EVERY \
            site inside that function — a second copy added to an already-registered `fn` \
            is inherited SILENTLY. Deliberate trade: a line key would fire on every \
            unrelated edit that shifts a line number, which is the churn that trains a \
            reader to paste past a gate without reading it.\n",
        REGISTERED_INLINE_BODIES.len()
    );
    let _ = err.flush();
}

#[test]
fn no_unnamed_lock_recovery_duplicate_exists() {
    let (occurrences, files) = collect_occurrences();

    // ANTI-VACUOUS, ASSERTED FIRST, and anchored on something that MUST exist: all three
    // `fn` definitions inside the chokepoint itself. A rename breaks this loudly, which is
    // the point, and it cannot pass on an empty walk. A scanner that finds nothing and
    // passes is this very defect wearing the opposite sign, and it is quieter than the bug.
    assert!(
        files > 50,
        "anti-vacuous: the walk found only {files} file(s) under src/ — the scan is broken, \
         and this is a REFUSAL, not a clean tree"
    );
    let chokepoint_defs = occurrences
        .iter()
        .filter(|o| o.path == CHOKEPOINT_FILE && o.kind == OccurrenceKind::Definition)
        .count();
    assert_eq!(
        chokepoint_defs, 3,
        "anti-vacuous: expected to see all 3 helper definitions inside {CHOKEPOINT_FILE}, \
         saw {chokepoint_defs}. Either the scanner is broken or a helper was renamed — \
         either way this is a REFUSAL, not a clean tree"
    );

    let violations = classify(&occurrences, REGISTERED_INLINE_BODIES);
    assert!(
        violations.is_empty(),
        "lock-recovery chokepoint violated:\n  - {}",
        violations
            .iter()
            .map(LockViolation::message)
            .collect::<Vec<_>>()
            .join("\n  - ")
    );

    write_limits(&occurrences, files);
}

#[test]
fn every_register_entry_has_a_reason_a_human_wrote() {
    assert!(
        !REGISTERED_INLINE_BODIES.is_empty(),
        "the register ships with the 5 measured inlined sites; an empty one would mean the \
         scan stopped finding them"
    );
    for (path, context, reason) in REGISTERED_INLINE_BODIES {
        assert!(
            !reason.trim().is_empty(),
            "({path}, {context}) has no reason — an unnamed debt wearing a name is not a name"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn occ(path: &str, context: &str, kind: OccurrenceKind) -> Occurrence {
        Occurrence {
            path: path.to_string(),
            line: 1,
            context: context.to_string(),
            kind,
        }
    }

    #[test]
    fn an_unregistered_definition_is_fatal_and_prints_both_remedies() {
        // Fabricated input — never a real copy planted in src/.
        let found = vec![occ("src/fake.rs", "helper", OccurrenceKind::Definition)];
        let v = classify(&found, &[]);
        assert_eq!(v.len(), 1);
        let msg = v[0].message();
        assert!(msg.contains("src/fake.rs"), "names the file: {msg}");
        assert!(msg.contains("DEFINES"), "names WHICH kind was hit: {msg}");
        assert!(
            msg.contains("crate::sync_util"),
            "route-it remedy first: {msg}"
        );
        assert!(
            msg.contains("(\"src/fake.rs\", \"helper\","),
            "prints the pasteable register line: {msg}"
        );
        assert!(msg.contains("forbids an unnamed one"), "{msg}");
    }

    #[test]
    fn an_unregistered_inlined_body_names_the_other_kind() {
        let found = vec![occ("src/fake.rs", "f", OccurrenceKind::InlinedBody)];
        let v = classify(&found, &[]);
        assert_eq!(v.len(), 1);
        assert!(
            v[0].message().contains("hand-inlines"),
            "a definition and an inlined body must not share one message"
        );
    }

    #[test]
    fn the_ratchet_fires_when_a_registered_site_is_gone() {
        let v = classify(&[], &[("src/gone.rs", "f", "why")]);
        assert_eq!(v.len(), 1);
        let msg = v[0].message();
        assert!(msg.contains("The debt is paid"), "{msg}");
        assert!(msg.contains("delete that line"), "pasteable delete: {msg}");
    }

    #[test]
    fn an_empty_reason_is_fatal_on_its_own_branch() {
        let found = vec![occ("src/a.rs", "f", OccurrenceKind::InlinedBody)];
        let v = classify(&found, &[("src/a.rs", "f", "   ")]);
        assert!(
            v.iter()
                .any(|x| matches!(x, LockViolation::EmptyReason { .. })),
            "whitespace-only reason must be fatal: {v:?}"
        );
    }

    #[test]
    fn the_chokepoint_file_is_exempt_by_definition() {
        let found = vec![
            occ(
                CHOKEPOINT_FILE,
                "lock_or_recover",
                OccurrenceKind::Definition,
            ),
            occ(
                CHOKEPOINT_FILE,
                "lock_or_recover",
                OccurrenceKind::InlinedBody,
            ),
        ];
        assert!(classify(&found, &[]).is_empty());
    }

    #[test]
    fn a_registered_site_is_silent() {
        let found = vec![occ("src/a.rs", "f", OccurrenceKind::InlinedBody)];
        assert!(classify(&found, &[("src/a.rs", "f", "measured debt")]).is_empty());
    }

    // ---- near-miss guards: the half that matters ----

    #[test]
    fn an_ordinary_call_is_not_a_definition() {
        let names = helper_names();
        // A discriminator that cannot tell a CALL from a DEFINITION is the whole defect
        // one layer up — that confusion is what let a false claim live for 84 days.
        for call in [
            "    let g = crate::sync_util::rw_read_or_recover(&x);",
            "    let g = sync_util::lock_or_recover(&m);",
            "    use crate::sync_util::{lock_or_recover, rw_write_or_recover};",
            "    rw_write_or_recover(&self.inner).push(1);",
        ] {
            assert!(
                !defines_helper(call, &names),
                "a call must not read as a definition: {call}"
            );
        }
        for def in [
            "pub fn lock_or_recover<T>(mutex: &Mutex<T>) -> MutexGuard<'_, T> {",
            "fn rw_read_or_recover<T>(lock: &RwLock<T>) -> RwLockReadGuard<'_, T> {",
            "    pub(crate) fn rw_write_or_recover<T>(l: &RwLock<T>) -> Guard<'_, T> {",
        ] {
            assert!(
                defines_helper(def, &names),
                "a definition must be seen: {def}"
            );
        }
        // Anti-vacuous on the discriminator itself: a same-prefix name must not fire.
        assert!(!defines_helper("fn lock_or_recover_twice() {", &names));
    }

    #[test]
    fn a_skip_on_poison_site_is_not_a_bypass() {
        // Limit 2, asserted rather than merely stated: those 13 sites are a DIFFERENT
        // POLICY (skip the work, not recover it), so firing on them would push a
        // behaviour change dressed as a dedup.
        for skip in [
            "        if let Ok(g) = m.lock() {",
            "        if let Some(g) = m.lock().ok() {",
            "        let Some(g) = self.inner.read().ok() else { return; };",
        ] {
            assert!(
                !inlines_recovery_body(skip),
                "skip-on-poison must be silent: {skip}"
            );
        }
    }

    #[test]
    fn the_inlined_body_is_matched_by_shape_not_by_a_closure_name() {
        for line in [
            "    let g = M.lock().unwrap_or_else(|e| e.into_inner());",
            "    let g = M.lock().unwrap_or_else(|poisoned| poisoned.into_inner());",
            "    let g = M.read().unwrap_or_else(|err| err.into_inner());",
        ] {
            assert!(inlines_recovery_body(line), "shape match must hold: {line}");
        }
        assert!(!inlines_recovery_body(
            "    let x = v.unwrap_or_else(|| 0);"
        ));
        assert!(!inlines_recovery_body("    let x = e.into_inner();"));
    }

    #[test]
    fn truncation_keys_on_a_module_level_mod_not_a_bare_cfg_test() {
        // src/git.rs carries item-level `#[cfg(test)]` at COLUMN 0 followed by `const`
        // and `fn`; a bare split would blank its entire production half.
        let attr = format!("#[cfg{}]", "(test)");
        let git_shape = vec![
            attr.as_str(),
            "const DESTRUCTIVE: &[&str] = &[];",
            "fn real_production_code() {}",
            attr.as_str(),
            "mod tests {",
        ];
        assert_eq!(
            test_region_start(&git_shape),
            Some(3),
            "must truncate at the module-level marker, not the first bare attribute"
        );
        assert_eq!(test_region_start(&["fn a() {}"]), None);
    }

    #[test]
    fn scan_file_ignores_the_test_region() {
        let attr = format!("#[cfg{}]", "(test)");
        let src = format!(
            "fn prod() {{\n    let g = M.lock().unwrap_or_else(|e| e.into_inner());\n}}\n\
             {attr}\nmod tests {{\n    fn t() {{ let g = M.lock().unwrap_or_else(|e| e.into_inner()); }}\n}}\n"
        );
        let found = scan_file("src/x.rs", &src, &helper_names());
        assert_eq!(found.len(), 1, "only the production-region site: {found:?}");
        assert_eq!(found[0].context, "prod");
        assert_eq!(found[0].line, 2);
    }
}
