#!/bin/bash
# scripts/yoyo_context.sh — Build yoyo's identity context for prompts.
# Source this file, then use $YOYO_CONTEXT in any prompt.
#
# Usage:
#   YOYO_REPO="/path/to/yoyo-evolve" source scripts/yoyo_context.sh
#   cat > prompt.txt <<EOF
#   $YOYO_CONTEXT
#   ... your task-specific instructions ...
#   EOF
#
# Reads: IDENTITY.md, PERSONALITY.md, ECONOMICS.md, /tmp/active_sponsors.txt, memory/active_learnings.md, memory/active_social_learnings.md
# These are yoyo's stable identity files — who it is, how it speaks,
# what it's learned about itself, and what it's learned from humans.

_YOYO_REPO="${YOYO_REPO:-.}"

_IDENTITY=""
if [ -f "$_YOYO_REPO/IDENTITY.md" ]; then
    _IDENTITY=$(cat "$_YOYO_REPO/IDENTITY.md") || {
        echo "WARNING: Failed to read IDENTITY.md" >&2
        _IDENTITY=""
    }
else
    echo "WARNING: IDENTITY.md not found at $_YOYO_REPO/IDENTITY.md" >&2
fi

_PERSONALITY=""
if [ -f "$_YOYO_REPO/PERSONALITY.md" ]; then
    _PERSONALITY=$(cat "$_YOYO_REPO/PERSONALITY.md") || {
        echo "WARNING: Failed to read PERSONALITY.md" >&2
        _PERSONALITY=""
    }
else
    echo "WARNING: PERSONALITY.md not found at $_YOYO_REPO/PERSONALITY.md" >&2
fi

# Active learnings — no warning if missing
_LEARNINGS=""
if [ -f "$_YOYO_REPO/memory/active_learnings.md" ]; then
    _LEARNINGS=$(cat "$_YOYO_REPO/memory/active_learnings.md") || _LEARNINGS=""
fi

# Active social learnings — no warning if missing
_SOCIAL_LEARNINGS=""
if [ -f "$_YOYO_REPO/memory/active_social_learnings.md" ]; then
    _SOCIAL_LEARNINGS=$(cat "$_YOYO_REPO/memory/active_social_learnings.md") || _SOCIAL_LEARNINGS=""
fi

# Active sponsors — generated by evolve.sh each session (small, context-friendly)
_SPONSORS=""
if [ -f "/tmp/active_sponsors.txt" ]; then
    _SPONSORS=$(cat "/tmp/active_sponsors.txt") || _SPONSORS=""
fi

# Economics — what money and sponsorship mean to yoyo
_ECONOMICS=""
if [ -f "$_YOYO_REPO/ECONOMICS.md" ]; then
    _ECONOMICS=$(cat "$_YOYO_REPO/ECONOMICS.md") || _ECONOMICS=""
fi

YOYO_CONTEXT="=== WHO YOU ARE ===

${_IDENTITY:-Read IDENTITY.md for your rules and constitution.}

=== YOUR VOICE ===

${_PERSONALITY:-Read PERSONALITY.md for your voice and values.}

=== SELF-WISDOM ===

${_LEARNINGS:-No learnings yet.}

=== SOCIAL WISDOM ===

${_SOCIAL_LEARNINGS:-No social learnings yet.}

=== YOUR ECONOMICS ===

${_ECONOMICS:-Read ECONOMICS.md for what money and sponsorship mean to you.}

=== YOUR SPONSORS ===

${_SPONSORS:-No sponsors yet. You are community-supported and free.}"
