//! Interactive first-run onboarding wizard.
//!
//! Detects when no API key or config file is present and walks the user through
//! choosing a provider, entering an API key, picking a model, and optionally
//! saving a `.yoyo.toml` config file — then proceeds directly into the REPL.

use crate::cli::{default_model_for_provider, known_models_for_provider, provider_api_key_env};
use crate::format::*;
use std::io::{self, BufRead, Write};

/// Providers offered in the interactive wizard menu (subset of KNOWN_PROVIDERS
/// that most users will care about, in a friendly order).
pub const WIZARD_PROVIDERS: &[(&str, &str)] = &[
    ("anthropic", "Anthropic (Claude)"),
    ("openai", "OpenAI (GPT-4o)"),
    ("google", "Google (Gemini)"),
    ("ollama", "Ollama (local, no API key needed)"),
    ("openrouter", "OpenRouter (multi-provider gateway)"),
    ("deepseek", "DeepSeek"),
    ("groq", "Groq"),
    ("xai", "xAI (Grok)"),
    ("mistral", "Mistral"),
];

/// Result of a successful wizard run.
#[derive(Debug, Clone, PartialEq)]
pub struct WizardResult {
    pub provider: String,
    pub api_key: String,
    pub model: String,
}

/// Generate a `.yoyo.toml` config string from wizard results.
pub fn generate_config_contents(provider: &str, model: &str) -> String {
    let mut config = String::new();
    config.push_str("# yoyo configuration — generated by setup wizard\n");
    config.push_str(&format!("provider = \"{provider}\"\n"));
    config.push_str(&format!("model = \"{model}\"\n"));
    config
}

/// Save a `.yoyo.toml` config file in the current directory.
/// Returns Ok(path) on success.
pub fn save_config_to_file(provider: &str, model: &str) -> io::Result<String> {
    let path = ".yoyo.toml";
    let contents = generate_config_contents(provider, model);
    std::fs::write(path, contents)?;
    Ok(path.to_string())
}

/// Parse a provider selection number (1-based) from user input.
/// Returns the provider slug if the number is valid, None otherwise.
pub fn parse_provider_choice(input: &str) -> Option<&'static str> {
    let trimmed = input.trim();
    // Allow typing the provider name directly
    for &(slug, _) in WIZARD_PROVIDERS {
        if trimmed.eq_ignore_ascii_case(slug) {
            return Some(slug);
        }
    }
    // Allow typing a number
    if let Ok(n) = trimmed.parse::<usize>() {
        if n >= 1 && n <= WIZARD_PROVIDERS.len() {
            return Some(WIZARD_PROVIDERS[n - 1].0);
        }
    }
    None
}

/// Run the interactive setup wizard, reading from `reader` and writing to `writer`.
/// This is the testable core — the public `run_setup_wizard()` wraps it with stdin/stdout.
///
/// Returns `Some(WizardResult)` on success, `None` if the user cancels (Ctrl-C / empty input).
pub fn run_wizard_interactive<R: BufRead, W: Write>(
    reader: &mut R,
    writer: &mut W,
) -> Option<WizardResult> {
    // Header
    writeln!(writer).ok();
    writeln!(writer, "  {BOLD}Welcome to yoyo! 🐙{RESET}").ok();
    writeln!(writer).ok();
    writeln!(
        writer,
        "  Let's get you set up. This will only take a moment."
    )
    .ok();
    writeln!(writer).ok();

    // Step 1: Choose provider
    writeln!(writer, "  {BOLD}Step 1:{RESET} Choose your AI provider:").ok();
    writeln!(writer).ok();
    for (i, &(_, label)) in WIZARD_PROVIDERS.iter().enumerate() {
        writeln!(writer, "    {BOLD}{}{RESET}. {label}", i + 1).ok();
    }
    writeln!(writer).ok();
    write!(writer, "  Enter number or name [1]: ").ok();
    writer.flush().ok();

    let mut choice = String::new();
    if reader.read_line(&mut choice).is_err() || choice.trim().is_empty() {
        // Default to anthropic
        choice = "1".to_string();
    }

    let provider = match parse_provider_choice(&choice) {
        Some(p) => p,
        None => {
            // Default to anthropic on bad input
            writeln!(writer, "  {DIM}(defaulting to Anthropic){RESET}").ok();
            "anthropic"
        }
    };

    let provider_label = WIZARD_PROVIDERS
        .iter()
        .find(|&&(slug, _)| slug == provider)
        .map(|&(_, label)| label)
        .unwrap_or(provider);

    writeln!(writer).ok();
    writeln!(
        writer,
        "  {GREEN}✓{RESET} Provider: {BOLD}{provider_label}{RESET}"
    )
    .ok();

    // Step 2: API key (skip for ollama)
    let api_key = if provider == "ollama" || provider == "custom" {
        writeln!(writer).ok();
        writeln!(
            writer,
            "  {DIM}No API key needed for {provider} — nice!{RESET}"
        )
        .ok();
        "not-needed".to_string()
    } else {
        let env_var = provider_api_key_env(provider).unwrap_or("ANTHROPIC_API_KEY");
        writeln!(writer).ok();
        writeln!(writer, "  {BOLD}Step 2:{RESET} Enter your API key").ok();
        writeln!(
            writer,
            "  {DIM}(or set {env_var} in your shell and press Enter to skip){RESET}"
        )
        .ok();
        writeln!(writer).ok();
        write!(writer, "  API key: ").ok();
        writer.flush().ok();

        let mut key_input = String::new();
        if reader.read_line(&mut key_input).is_err() {
            return None;
        }
        let key = key_input.trim().to_string();

        if key.is_empty() {
            // Check environment
            if let Some(env_key) = provider_api_key_env(provider) {
                if let Ok(val) = std::env::var(env_key) {
                    if !val.is_empty() {
                        writeln!(
                            writer,
                            "  {GREEN}✓{RESET} Using key from {DIM}{env_key}{RESET}"
                        )
                        .ok();
                        val
                    } else {
                        writeln!(
                            writer,
                            "  {YELLOW}No API key provided.{RESET} Set {env_var} or re-run the wizard."
                        )
                        .ok();
                        return None;
                    }
                } else {
                    writeln!(
                        writer,
                        "  {YELLOW}No API key provided.{RESET} Set {env_var} or re-run the wizard."
                    )
                    .ok();
                    return None;
                }
            } else {
                writeln!(
                    writer,
                    "  {YELLOW}No API key provided.{RESET} Set {env_var} or re-run the wizard."
                )
                .ok();
                return None;
            }
        } else {
            writeln!(writer, "  {GREEN}✓{RESET} API key received").ok();
            key
        }
    };

    // Step 3: Model preference
    let default_model = default_model_for_provider(provider);
    let known_models = known_models_for_provider(provider);

    writeln!(writer).ok();
    writeln!(
        writer,
        "  {BOLD}Step 3:{RESET} Choose a model {DIM}(press Enter for default){RESET}"
    )
    .ok();

    if !known_models.is_empty() {
        writeln!(writer, "  {DIM}Popular models for {provider}:{RESET}").ok();
        for m in known_models {
            if *m == default_model {
                writeln!(writer, "    • {m} {DIM}(default){RESET}").ok();
            } else {
                writeln!(writer, "    • {m}").ok();
            }
        }
    }
    writeln!(writer).ok();
    write!(writer, "  Model [{default_model}]: ").ok();
    writer.flush().ok();

    let mut model_input = String::new();
    if reader.read_line(&mut model_input).is_err() {
        return None;
    }
    let model = model_input.trim();
    let model = if model.is_empty() {
        default_model.clone()
    } else {
        model.to_string()
    };

    writeln!(writer, "  {GREEN}✓{RESET} Model: {BOLD}{model}{RESET}").ok();

    // Step 4: Offer to save config
    writeln!(writer).ok();
    writeln!(
        writer,
        "  {BOLD}Step 4:{RESET} Save configuration to {CYAN}.yoyo.toml{RESET}?"
    )
    .ok();
    writeln!(
        writer,
        "  {DIM}This saves your provider and model so you don't need flags next time.{RESET}"
    )
    .ok();
    writeln!(writer).ok();
    write!(writer, "  Save config? [Y/n]: ").ok();
    writer.flush().ok();

    let mut save_input = String::new();
    if reader.read_line(&mut save_input).is_err() {
        // Default to yes on read error
        save_input = "y".to_string();
    }
    let save_choice = save_input.trim().to_lowercase();

    if save_choice.is_empty() || save_choice == "y" || save_choice == "yes" {
        match save_config_to_file(provider, &model) {
            Ok(path) => {
                writeln!(writer, "  {GREEN}✓{RESET} Saved to {CYAN}{path}{RESET}").ok();
            }
            Err(e) => {
                writeln!(writer, "  {YELLOW}Could not save config: {e}{RESET}").ok();
            }
        }
    } else {
        writeln!(
            writer,
            "  {DIM}Skipped — you can create .yoyo.toml manually later.{RESET}"
        )
        .ok();
    }

    writeln!(writer).ok();
    writeln!(writer, "  {GREEN}{BOLD}All set! Starting yoyo...{RESET}").ok();
    writeln!(writer).ok();

    Some(WizardResult {
        provider: provider.to_string(),
        api_key,
        model,
    })
}

/// Run the interactive setup wizard with stdin/stdout.
/// Returns `Some(WizardResult)` on success, `None` if cancelled.
pub fn run_setup_wizard() -> Option<WizardResult> {
    let stdin = io::stdin();
    let mut reader = stdin.lock();
    let mut writer = io::stdout();
    run_wizard_interactive(&mut reader, &mut writer)
}

/// Check whether we should offer the setup wizard.
/// Returns true when there's no API key from any source and no config file.
pub fn needs_setup(provider: &str) -> bool {
    // Check if config file exists
    if std::path::Path::new(".yoyo.toml").exists() {
        return false;
    }
    // Check user-level config
    if let Some(user_path) = crate::cli::user_config_path() {
        if user_path.exists() {
            return false;
        }
    }
    // For ollama/custom, no setup needed
    if provider == "ollama" || provider == "custom" {
        return false;
    }
    // Check if any API key env var is set
    if let Some(env_var) = provider_api_key_env(provider) {
        if std::env::var(env_var)
            .ok()
            .filter(|k| !k.is_empty())
            .is_some()
        {
            return false;
        }
    }
    // Also check generic fallbacks
    if std::env::var("ANTHROPIC_API_KEY")
        .ok()
        .filter(|k| !k.is_empty())
        .is_some()
    {
        return false;
    }
    if std::env::var("API_KEY")
        .ok()
        .filter(|k| !k.is_empty())
        .is_some()
    {
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::KNOWN_PROVIDERS;

    #[test]
    fn test_parse_provider_choice_by_number() {
        assert_eq!(parse_provider_choice("1"), Some("anthropic"));
        assert_eq!(parse_provider_choice("2"), Some("openai"));
        assert_eq!(parse_provider_choice("3"), Some("google"));
        assert_eq!(parse_provider_choice("4"), Some("ollama"));
        assert_eq!(parse_provider_choice("5"), Some("openrouter"));
    }

    #[test]
    fn test_parse_provider_choice_by_name() {
        assert_eq!(parse_provider_choice("anthropic"), Some("anthropic"));
        assert_eq!(parse_provider_choice("OpenAI"), Some("openai"));
        assert_eq!(parse_provider_choice("GOOGLE"), Some("google"));
        assert_eq!(parse_provider_choice("ollama"), Some("ollama"));
    }

    #[test]
    fn test_parse_provider_choice_invalid() {
        assert_eq!(parse_provider_choice("0"), None);
        assert_eq!(parse_provider_choice("99"), None);
        assert_eq!(parse_provider_choice("banana"), None);
        assert_eq!(parse_provider_choice(""), None);
    }

    #[test]
    fn test_parse_provider_choice_whitespace() {
        assert_eq!(parse_provider_choice("  1  "), Some("anthropic"));
        assert_eq!(parse_provider_choice("  openai  "), Some("openai"));
    }

    #[test]
    fn test_generate_config_contents() {
        let config = generate_config_contents("anthropic", "claude-opus-4-6");
        assert!(config.contains("provider = \"anthropic\""));
        assert!(config.contains("model = \"claude-opus-4-6\""));
        assert!(config.starts_with("# yoyo configuration"));
    }

    #[test]
    fn test_generate_config_openai() {
        let config = generate_config_contents("openai", "gpt-4o");
        assert!(config.contains("provider = \"openai\""));
        assert!(config.contains("model = \"gpt-4o\""));
    }

    #[test]
    fn test_wizard_providers_are_known() {
        for &(slug, _) in WIZARD_PROVIDERS {
            assert!(
                KNOWN_PROVIDERS.contains(&slug),
                "Wizard provider '{slug}' not in KNOWN_PROVIDERS"
            );
        }
    }

    #[test]
    fn test_wizard_anthropic_with_key() {
        // Simulate: choose anthropic (1), enter a key, accept default model, save=no
        let input = "1\nsk-test-key-123\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "anthropic");
        assert_eq!(r.api_key, "sk-test-key-123");
        assert_eq!(r.model, "claude-opus-4-6"); // default

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("Step 1"));
        assert!(output_str.contains("Step 2"));
        assert!(output_str.contains("Step 3"));
        assert!(output_str.contains("Step 4"));
        assert!(output_str.contains("All set!"));
    }

    #[test]
    fn test_wizard_ollama_skips_api_key() {
        // Choose ollama (4), pick default model, save=no
        let input = "4\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "ollama");
        assert_eq!(r.api_key, "not-needed");
        assert_eq!(r.model, "llama3.2"); // default for ollama

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("No API key needed"));
    }

    #[test]
    fn test_wizard_custom_model() {
        // Choose openai (2), enter key, type custom model, save=no
        let input = "2\nsk-openai-key\ngpt-4.1-mini\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "openai");
        assert_eq!(r.api_key, "sk-openai-key");
        assert_eq!(r.model, "gpt-4.1-mini");
    }

    #[test]
    fn test_wizard_provider_by_name() {
        // Type provider name instead of number
        let input = "google\ntest-key\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "google");
        assert_eq!(r.api_key, "test-key");
    }

    #[test]
    fn test_wizard_default_provider_on_enter() {
        // Just press enter for provider (defaults to anthropic), then enter key, etc.
        let input = "\nmy-api-key\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "anthropic");
        assert_eq!(r.api_key, "my-api-key");
    }

    #[test]
    fn test_wizard_no_key_no_env_returns_none() {
        // Choose anthropic, enter empty key with no env var set
        // We need to make sure the env var is not set for this test
        let input = "1\n\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        // Temporarily unset the env var if set
        let prev = std::env::var("ANTHROPIC_API_KEY").ok();
        std::env::remove_var("ANTHROPIC_API_KEY");

        let result = run_wizard_interactive(&mut reader, &mut output);

        // Restore
        if let Some(val) = prev {
            std::env::set_var("ANTHROPIC_API_KEY", val);
        }

        assert!(result.is_none());
        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("No API key provided"));
    }

    #[test]
    fn test_save_config_to_file() {
        // Use a temp dir to avoid polluting the project
        let dir = std::env::temp_dir().join("yoyo_test_wizard");
        let _ = std::fs::create_dir_all(&dir);
        let prev_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(&dir).unwrap();

        let result = save_config_to_file("openai", "gpt-4o");
        assert!(result.is_ok());

        let content = std::fs::read_to_string(".yoyo.toml").unwrap();
        assert!(content.contains("provider = \"openai\""));
        assert!(content.contains("model = \"gpt-4o\""));

        // Cleanup
        std::env::set_current_dir(prev_dir).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_wizard_result_fields() {
        let result = WizardResult {
            provider: "anthropic".to_string(),
            api_key: "sk-test".to_string(),
            model: "claude-opus-4-6".to_string(),
        };
        assert_eq!(result.provider, "anthropic");
        assert_eq!(result.api_key, "sk-test");
        assert_eq!(result.model, "claude-opus-4-6");
    }
}
