//! Interactive first-run onboarding wizard.
//!
//! Detects when no API key or config file is present and walks the user through
//! choosing a provider, entering an API key, picking a model, and optionally
//! saving a `.yoyo.toml` config file — then proceeds directly into the REPL.

use crate::cli::{default_model_for_provider, known_models_for_provider, provider_api_key_env};
use crate::format::*;
use std::io::{self, BufRead, Write};

/// Providers offered in the interactive wizard menu (subset of KNOWN_PROVIDERS
/// that most users will care about, in a friendly order).
pub const WIZARD_PROVIDERS: &[(&str, &str)] = &[
    ("anthropic", "Anthropic (Claude)"),
    ("openai", "OpenAI (GPT-4o)"),
    ("google", "Google (Gemini)"),
    ("ollama", "Ollama (local, no API key needed)"),
    ("openrouter", "OpenRouter (multi-provider gateway)"),
    ("deepseek", "DeepSeek"),
    ("groq", "Groq"),
    ("xai", "xAI (Grok)"),
    ("mistral", "Mistral"),
    ("cerebras", "Cerebras"),
    ("minimax", "MiniMax"),
    (
        "bedrock",
        "AWS Bedrock (Claude, Nova — uses AWS credentials)",
    ),
    (
        "github",
        "GitHub Models (GPT-4o, Claude, Llama — uses GITHUB_TOKEN)",
    ),
    ("custom", "Custom (self-hosted OpenAI-compatible)"),
];

/// Result of a successful wizard run.
#[derive(Debug, Clone, PartialEq)]
pub struct WizardResult {
    pub provider: String,
    pub api_key: String,
    pub model: String,
    pub base_url: Option<String>,
}

/// Escape a value for a TOML basic string (`"..."`).
/// Only the two characters that can break out of the quotes matter here —
/// API keys are read from a trimmed single line, so no control chars.
fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Should this key be offered for persistence at all?
/// Ollama's placeholder isn't a secret, and a blank key is nothing to save.
pub fn key_is_savable(provider: &str, key: &str) -> bool {
    provider != "ollama" && !key.trim().is_empty()
}

/// Parse a yes/no answer where anything but an explicit yes means **no**.
/// Writing a secret to disk is opt-in, so the default must be the safe one.
pub fn parse_yes_default_no(input: &str) -> bool {
    matches!(input.trim().to_lowercase().as_str(), "y" | "yes")
}

/// Explain how to supply the API key when it was NOT written to a config file.
/// Never leave a user who just typed a secret with no route to using it (#628).
pub fn key_not_saved_notice(provider: &str, config_path: Option<&str>) -> String {
    let mut out = String::from("Your key was not saved. Set it before starting yoyo:\n");
    if provider == "bedrock" {
        out.push_str("  export AWS_ACCESS_KEY_ID=\"…\"\n");
        out.push_str("  export AWS_SECRET_ACCESS_KEY=\"…\"\n");
    } else {
        let env_var = provider_api_key_env(provider).unwrap_or("ANTHROPIC_API_KEY");
        out.push_str(&format!("  export {env_var}=\"…\"\n"));
    }
    match config_path {
        Some(path) => out.push_str(&format!("(or add `api_key = \"…\"` to {path})\n")),
        None => out.push_str("(or add `api_key = \"…\"` to a .yoyo.toml config file)\n"),
    }
    out
}

/// Generate a `.yoyo.toml` config string from wizard results.
/// `api_key` is written only when `Some` and non-blank — an empty key is
/// treated as absent, never emitted as `api_key = ""`.
pub fn generate_config_contents(
    provider: &str,
    model: &str,
    base_url: Option<&str>,
    api_key: Option<&str>,
) -> String {
    let mut config = String::new();
    config.push_str("# yoyo configuration — generated by setup wizard\n");
    config.push_str(&format!("provider = \"{provider}\"\n"));
    config.push_str(&format!("model = \"{model}\"\n"));
    if let Some(url) = base_url {
        config.push_str(&format!("base_url = \"{url}\"\n"));
    }
    if let Some(key) = api_key.filter(|k| !k.trim().is_empty()) {
        config.push_str("# This file contains a secret — keep it out of version control.\n");
        config.push_str(&format!("api_key = \"{}\"\n", toml_escape(key)));
    }
    if provider == "bedrock" {
        config.push_str("# For Bedrock, set: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY\n");
        config.push_str("# Or pass --api-key \"access_key:secret_key\"\n");
    }
    config
}

/// Save a `.yoyo.toml` config file in the given directory.
/// If the file already exists, it is backed up to `.yoyo.toml.bak` first and
/// unmanaged top-level keys are preserved into the new contents.
/// Returns Ok(path) on success.
pub fn save_config_to_file(
    dir: &std::path::Path,
    provider: &str,
    model: &str,
    base_url: Option<&str>,
    api_key: Option<&str>,
) -> io::Result<String> {
    let path = dir.join(".yoyo.toml");
    let contents = generate_config_contents(provider, model, base_url, api_key);
    write_config_with_backup(&path, contents)?;
    if api_key.is_some_and(|k| !k.trim().is_empty()) {
        restrict_config_permissions(&path);
    }
    Ok(path.display().to_string())
}

/// Tighten a config file that holds a secret to owner-only (`0600`) on unix.
/// A chmod failure must never abort the save — the config is already written,
/// so we warn and continue rather than pretend the save failed.
fn restrict_config_permissions(path: &std::path::Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Err(e) = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600)) {
            eprintln!(
                "  {YELLOW}Warning:{RESET} could not restrict permissions on {} ({e}) — it contains your API key.",
                path.display()
            );
        }
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
}

/// Top-level keys the setup wizard manages in `generate_config_contents`.
/// Anything else found at the top level of an existing config is preserved.
/// `api_key` is managed: without it here, a previously-written key would be
/// duplicated into the "preserved from previous config" block (#628).
const MANAGED_CONFIG_KEYS: &[&str] = &["provider", "model", "base_url", "api_key"];

/// Scan an existing config's top-level `key = value` lines and return those
/// whose key is NOT managed by the wizard (e.g. `auto_watch = true`).
/// The scan is deliberately line-based and stops at the first `[section]`
/// header — keys inside sections are not top-level and must not be appended.
fn preserved_unmanaged_lines(old_contents: &str) -> Vec<String> {
    let mut preserved = Vec::new();
    for line in old_contents.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            break; // section keys are not top-level — stop scanning
        }
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some((key, _value)) = trimmed.split_once('=') {
            if !MANAGED_CONFIG_KEYS.contains(&key.trim()) {
                preserved.push(trimmed.to_string());
            }
        }
    }
    preserved
}

/// Write `contents` to `path`. If `path` already exists, first copy it to
/// `<path>.bak` and append any unmanaged top-level keys from the old file
/// under a `# preserved from previous config` comment.
fn write_config_with_backup(path: &std::path::Path, mut contents: String) -> io::Result<()> {
    if path.exists() {
        let old_contents = std::fs::read_to_string(path)?;
        std::fs::copy(path, backup_path(path))?;
        let preserved = preserved_unmanaged_lines(&old_contents);
        if !preserved.is_empty() {
            contents.push_str("\n# preserved from previous config\n");
            for line in preserved {
                contents.push_str(&line);
                contents.push('\n');
            }
        }
    }
    std::fs::write(path, contents)
}

/// `<path>.bak` — appends rather than replaces the extension
/// (`.yoyo.toml` → `.yoyo.toml.bak`).
fn backup_path(path: &std::path::Path) -> std::path::PathBuf {
    let mut os = path.as_os_str().to_owned();
    os.push(".bak");
    std::path::PathBuf::from(os)
}

/// Save config to the user-level XDG path (`~/.config/yoyo/config.toml`).
/// Creates parent directories if they don't exist. If the file already exists,
/// it is backed up to `config.toml.bak` first and unmanaged top-level keys are
/// preserved into the new contents.
/// Returns Ok(path_string) on success.
pub fn save_config_to_user_file(
    provider: &str,
    model: &str,
    base_url: Option<&str>,
    api_key: Option<&str>,
) -> io::Result<String> {
    let path = crate::cli::user_config_path().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::NotFound,
            "Could not determine user config directory (no HOME or XDG_CONFIG_HOME set)",
        )
    })?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let contents = generate_config_contents(provider, model, base_url, api_key);
    write_config_with_backup(&path, contents)?;
    if api_key.is_some_and(|k| !k.trim().is_empty()) {
        restrict_config_permissions(&path);
    }
    Ok(path.display().to_string())
}

/// Parse a provider selection number (1-based) from user input.
/// Returns the provider slug if the number is valid, None otherwise.
pub fn parse_provider_choice(input: &str) -> Option<&'static str> {
    let trimmed = input.trim();
    // Allow typing the provider name directly
    for &(slug, _) in WIZARD_PROVIDERS {
        if trimmed.eq_ignore_ascii_case(slug) {
            return Some(slug);
        }
    }
    // Allow typing a number
    if let Ok(n) = trimmed.parse::<usize>() {
        if n >= 1 && n <= WIZARD_PROVIDERS.len() {
            return Some(WIZARD_PROVIDERS[n - 1].0);
        }
    }
    None
}

/// Where the user wants to save their config.
#[derive(Debug, Clone, PartialEq)]
pub enum SaveLocation {
    /// Save to `.yoyo.toml` in the current directory.
    Project,
    /// Save to `~/.config/yoyo/config.toml` (user-level XDG path).
    User,
    /// Don't save.
    Skip,
}

/// Parse a save-location choice from wizard input.
/// "1" or "p"/"project" => Project, "2" or "u"/"user" => User,
/// "3" or "n"/"no"/"none"/"s"/"skip" => Skip. Default (empty) => Project.
pub fn parse_save_choice(input: &str) -> SaveLocation {
    let trimmed = input.trim().to_lowercase();
    match trimmed.as_str() {
        "" | "1" | "p" | "project" => SaveLocation::Project,
        "2" | "u" | "user" | "global" => SaveLocation::User,
        "3" | "n" | "no" | "none" | "s" | "skip" => SaveLocation::Skip,
        _ => SaveLocation::Project, // default
    }
}

/// Get a friendly display string for the user-level config path.
pub fn user_config_display_path() -> String {
    crate::cli::user_config_path()
        .map(|p| p.display().to_string())
        .unwrap_or_else(|| "~/.config/yoyo/config.toml".to_string())
}

/// Run the interactive setup wizard, reading from `reader` and writing to `writer`.
/// This is the testable core — the public `run_setup_wizard()` wraps it with stdin/stdout.
///
/// Returns `Some(WizardResult)` on success, `None` if the user cancels (Ctrl-C / empty input).
pub fn run_wizard_interactive<R: BufRead, W: Write>(
    reader: &mut R,
    writer: &mut W,
) -> Option<WizardResult> {
    // Header
    writeln!(writer).ok();
    writeln!(writer, "  {BOLD}Welcome to yoyo! 🐙{RESET}").ok();
    writeln!(writer).ok();
    writeln!(
        writer,
        "  Let's get you set up. This will only take a moment."
    )
    .ok();
    writeln!(writer).ok();

    // Step 1: Choose provider
    writeln!(writer, "  {BOLD}Step 1:{RESET} Choose your AI provider:").ok();
    writeln!(writer).ok();
    for (i, &(_, label)) in WIZARD_PROVIDERS.iter().enumerate() {
        writeln!(writer, "    {BOLD}{}{RESET}. {label}", i + 1).ok();
    }
    writeln!(writer).ok();
    write!(writer, "  Enter number or name [1]: ").ok();
    writer.flush().ok();

    let mut choice = String::new();
    if reader.read_line(&mut choice).is_err() || choice.trim().is_empty() {
        // Default to anthropic
        choice = "1".to_string();
    }

    let provider = match parse_provider_choice(&choice) {
        Some(p) => p,
        None => {
            // Default to anthropic on bad input
            writeln!(writer, "  {DIM}(defaulting to Anthropic){RESET}").ok();
            "anthropic"
        }
    };

    let provider_label = WIZARD_PROVIDERS
        .iter()
        .find(|&&(slug, _)| slug == provider)
        .map(|&(_, label)| label)
        .unwrap_or(provider);

    writeln!(writer).ok();
    writeln!(
        writer,
        "  {GREEN}✓{RESET} Provider: {BOLD}{provider_label}{RESET}"
    )
    .ok();

    // Step 2: API key (skip for ollama, special flow for bedrock)
    let (api_key, base_url_from_step2) = if provider == "ollama" {
        writeln!(writer).ok();
        writeln!(
            writer,
            "  {DIM}No API key needed for {provider} — nice!{RESET}"
        )
        .ok();
        ("not-needed".to_string(), None)
    } else if provider == "bedrock" {
        writeln!(writer).ok();
        writeln!(writer, "  {BOLD}Step 2:{RESET} Enter your AWS credentials").ok();
        writeln!(
            writer,
            "  {DIM}(or set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in your shell){RESET}"
        )
        .ok();
        writeln!(writer).ok();

        write!(writer, "  AWS Access Key ID: ").ok();
        writer.flush().ok();
        let mut access_key_input = String::new();
        if reader.read_line(&mut access_key_input).is_err() {
            return None;
        }
        let access_key = access_key_input.trim().to_string();

        write!(writer, "  AWS Secret Access Key: ").ok();
        writer.flush().ok();
        let mut secret_key_input = String::new();
        if reader.read_line(&mut secret_key_input).is_err() {
            return None;
        }
        let secret_key = secret_key_input.trim().to_string();

        write!(writer, "  AWS Region [us-east-1]: ").ok();
        writer.flush().ok();
        let mut region_input = String::new();
        if reader.read_line(&mut region_input).is_err() {
            return None;
        }
        let region = region_input.trim();
        let region = if region.is_empty() {
            "us-east-1"
        } else {
            region
        };

        // Build the combined key and base URL
        let combined_key = if access_key.is_empty() && secret_key.is_empty() {
            // Check environment variables
            let env_access = std::env::var("AWS_ACCESS_KEY_ID").unwrap_or_default();
            let env_secret = std::env::var("AWS_SECRET_ACCESS_KEY").unwrap_or_default();
            if !env_access.is_empty() && !env_secret.is_empty() {
                writeln!(
                    writer,
                    "  {GREEN}✓{RESET} Using credentials from {DIM}AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY{RESET}"
                )
                .ok();
                format!("{env_access}:{env_secret}")
            } else {
                writeln!(
                    writer,
                    "  {YELLOW}No AWS credentials provided.{RESET} Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or re-run the wizard."
                )
                .ok();
                return None;
            }
        } else {
            writeln!(writer, "  {GREEN}✓{RESET} AWS credentials received").ok();
            format!("{access_key}:{secret_key}")
        };

        let bedrock_url = format!("https://bedrock-runtime.{region}.amazonaws.com");
        writeln!(
            writer,
            "  {GREEN}✓{RESET} Region: {BOLD}{region}{RESET} → {DIM}{bedrock_url}{RESET}"
        )
        .ok();

        (combined_key, Some(bedrock_url))
    } else {
        let env_var = provider_api_key_env(provider).unwrap_or("ANTHROPIC_API_KEY");
        writeln!(writer).ok();
        writeln!(writer, "  {BOLD}Step 2:{RESET} Enter your API key").ok();
        writeln!(
            writer,
            "  {DIM}(or set {env_var} in your shell and press Enter to skip){RESET}"
        )
        .ok();
        writeln!(writer).ok();
        write!(writer, "  API key: ").ok();
        writer.flush().ok();

        let mut key_input = String::new();
        if reader.read_line(&mut key_input).is_err() {
            return None;
        }
        let key = key_input.trim().to_string();

        if key.is_empty() {
            // Check environment
            if let Some(env_key) = provider_api_key_env(provider) {
                if let Ok(val) = std::env::var(env_key) {
                    if !val.is_empty() {
                        writeln!(
                            writer,
                            "  {GREEN}✓{RESET} Using key from {DIM}{env_key}{RESET}"
                        )
                        .ok();
                        (val, None)
                    } else {
                        writeln!(
                            writer,
                            "  {YELLOW}No API key provided.{RESET} Set {env_var} or re-run the wizard."
                        )
                        .ok();
                        return None;
                    }
                } else {
                    writeln!(
                        writer,
                        "  {YELLOW}No API key provided.{RESET} Set {env_var} or re-run the wizard."
                    )
                    .ok();
                    return None;
                }
            } else {
                writeln!(
                    writer,
                    "  {YELLOW}No API key provided.{RESET} Set {env_var} or re-run the wizard."
                )
                .ok();
                return None;
            }
        } else {
            writeln!(writer, "  {GREEN}✓{RESET} API key received").ok();
            (key, None)
        }
    };

    // Base URL prompt (for custom/self-hosted providers, or pre-set by bedrock)
    let base_url = if base_url_from_step2.is_some() {
        base_url_from_step2
    } else if provider == "custom" {
        writeln!(writer).ok();
        writeln!(
            writer,
            "  {BOLD}Base URL:{RESET} Enter the URL of your OpenAI-compatible API"
        )
        .ok();
        writeln!(writer, "  {DIM}(e.g. http://localhost:8080/v1){RESET}").ok();
        writeln!(writer).ok();
        write!(writer, "  Base URL: ").ok();
        writer.flush().ok();

        let mut url_input = String::new();
        if reader.read_line(&mut url_input).is_err() {
            return None;
        }
        let url = url_input.trim().to_string();
        if url.is_empty() {
            writeln!(
                writer,
                "  {YELLOW}No base URL provided.{RESET} A base URL is required for custom providers."
            )
            .ok();
            return None;
        }
        writeln!(writer, "  {GREEN}✓{RESET} Base URL: {BOLD}{url}{RESET}").ok();
        Some(url)
    } else {
        None
    };

    // Step 3: Model preference
    let default_model = default_model_for_provider(provider);
    let known_models = known_models_for_provider(provider);

    writeln!(writer).ok();
    writeln!(
        writer,
        "  {BOLD}Step 3:{RESET} Choose a model {DIM}(press Enter for default){RESET}"
    )
    .ok();

    if !known_models.is_empty() {
        writeln!(writer, "  {DIM}Popular models for {provider}:{RESET}").ok();
        for m in known_models {
            if *m == default_model {
                writeln!(writer, "    • {m} {DIM}(default){RESET}").ok();
            } else {
                writeln!(writer, "    • {m}").ok();
            }
        }
    }
    writeln!(writer).ok();
    write!(writer, "  Model [{default_model}]: ").ok();
    writer.flush().ok();

    let mut model_input = String::new();
    if reader.read_line(&mut model_input).is_err() {
        return None;
    }
    let model = model_input.trim();
    let model = if model.is_empty() {
        default_model.clone()
    } else {
        model.to_string()
    };

    writeln!(writer, "  {GREEN}✓{RESET} Model: {BOLD}{model}{RESET}").ok();

    // Step 4: Offer to save config (three choices)
    let xdg_display = user_config_display_path();
    writeln!(writer).ok();
    writeln!(writer, "  {BOLD}Step 4:{RESET} Save configuration?").ok();
    writeln!(
        writer,
        "  {DIM}This saves your provider and model so you don't need flags next time.{RESET}"
    )
    .ok();
    writeln!(writer).ok();
    writeln!(
        writer,
        "    {BOLD}1{RESET}. Save to {CYAN}.yoyo.toml{RESET} (current project only)"
    )
    .ok();
    writeln!(
        writer,
        "    {BOLD}2{RESET}. Save to {CYAN}{xdg_display}{RESET} (user-level, applies everywhere)"
    )
    .ok();
    writeln!(writer, "    {BOLD}3{RESET}. Don't save").ok();
    writeln!(writer).ok();
    write!(writer, "  Choice [1]: ").ok();
    writer.flush().ok();

    let mut save_input = String::new();
    if reader.read_line(&mut save_input).is_err() {
        // Default to project on read error
        save_input = "1".to_string();
    }
    let save_location = parse_save_choice(&save_input);

    // Writing a secret to disk is opt-in: only ask when a file will actually be
    // written AND a real key was entered, and default the answer to No (#628).
    let key_savable = key_is_savable(provider, &api_key);
    let will_write_file = !matches!(save_location, SaveLocation::Skip);
    let save_key = if key_savable && will_write_file {
        writeln!(writer).ok();
        write!(writer, "  Save the API key to this file? [y/N]: ").ok();
        writer.flush().ok();
        let mut key_answer = String::new();
        if reader.read_line(&mut key_answer).is_err() {
            key_answer.clear();
        }
        parse_yes_default_no(&key_answer)
    } else {
        false
    };
    let key_arg = if save_key {
        Some(api_key.as_str())
    } else {
        None
    };
    // Path of the config file we actually wrote, and whether the key went in it.
    let mut written_path: Option<String> = None;
    let mut key_written = false;

    match save_location {
        SaveLocation::Project => {
            let target = std::env::current_dir().unwrap_or_default();
            let existed = target.join(".yoyo.toml").exists();
            match save_config_to_file(&target, provider, &model, base_url.as_deref(), key_arg) {
                Ok(path) => {
                    writeln!(writer, "  {GREEN}✓{RESET} Saved to {CYAN}{path}{RESET}").ok();
                    written_path = Some(path.clone());
                    key_written = save_key;
                    if existed {
                        writeln!(
                            writer,
                            "  {DIM}Previous config backed up to {path}.bak (unmanaged settings preserved){RESET}"
                        )
                        .ok();
                    }
                }
                Err(e) => {
                    writeln!(writer, "  {YELLOW}Could not save config: {e}{RESET}").ok();
                }
            }
        }
        SaveLocation::User => {
            let existed = crate::cli::user_config_path().is_some_and(|p| p.exists());
            match save_config_to_user_file(provider, &model, base_url.as_deref(), key_arg) {
                Ok(path) => {
                    writeln!(writer, "  {GREEN}✓{RESET} Saved to {CYAN}{path}{RESET}").ok();
                    written_path = Some(path.clone());
                    key_written = save_key;
                    if existed {
                        writeln!(
                            writer,
                            "  {DIM}Previous config backed up to {path}.bak (unmanaged settings preserved){RESET}"
                        )
                        .ok();
                    }
                }
                Err(e) => {
                    writeln!(writer, "  {YELLOW}Could not save config: {e}{RESET}").ok();
                }
            }
        }
        SaveLocation::Skip => {
            writeln!(
                writer,
                "  {DIM}Skipped — you can create .yoyo.toml or {xdg_display} manually later.{RESET}"
            )
            .ok();
        }
    }

    // Never leave someone who just typed a secret without a route to using it.
    if key_savable && !key_written {
        writeln!(writer).ok();
        for line in key_not_saved_notice(provider, written_path.as_deref()).lines() {
            writeln!(writer, "  {YELLOW}{line}{RESET}").ok();
        }
    }

    writeln!(writer).ok();
    writeln!(writer, "  {GREEN}{BOLD}All set! Starting yoyo...{RESET}").ok();
    writeln!(writer).ok();

    Some(WizardResult {
        provider: provider.to_string(),
        api_key,
        model,
        base_url,
    })
}

/// Run the interactive setup wizard with stdin/stdout.
/// Returns `Some(WizardResult)` on success, `None` if cancelled.
pub fn run_setup_wizard() -> Option<WizardResult> {
    let stdin = io::stdin();
    let mut reader = stdin.lock();
    let mut writer = io::stdout();
    run_wizard_interactive(&mut reader, &mut writer)
}

/// Pure decision helper: should we offer the setup wizard?
///
/// The question this answers is **"can yoyo actually start?"** — not "does a
/// config file exist?". The old existence check assumed a config file implied a
/// working config, so a half-configured file (provider + model, no key — exactly
/// what the wizard used to write) left the user stuck: yoyo couldn't run and the
/// wizard never offered itself again (#628).
///
/// Rules:
/// - `ollama` / `custom` never need a key (local models, custom `base_url`) → no setup
/// - any reachable key, from env **or** config → no setup
/// - no reachable key → offer the wizard, *regardless of whether a config exists*
///
/// (`config_exists` is deliberately not a parameter: it never changes the answer,
/// and carrying it would just re-invite the bug this fixes.)
pub(crate) fn needs_setup_from(provider: &str, key_from_env: bool, key_in_config: bool) -> bool {
    // Local / self-hosted providers authenticate differently (or not at all).
    // Never drag a local-model user into an API-key prompt.
    if provider == "ollama" || provider == "custom" {
        return false;
    }
    !(key_from_env || key_in_config)
}

/// Is there a non-empty top-level `api_key` in this config file content?
/// Reuses `cli::parse_config_file` — no second TOML parser.
fn config_content_has_api_key(content: &str) -> bool {
    crate::cli::parse_config_file(content)
        .get("api_key")
        .is_some_and(|k| !k.trim().is_empty())
}

/// Does any config file on the search path supply a usable `api_key`?
/// Same search order as `cli::load_config_file`, minus the "config: <path>"
/// chatter (this runs before the banner and shouldn't add noise).
fn api_key_in_config_files() -> bool {
    let mut paths: Vec<std::path::PathBuf> = vec![std::path::PathBuf::from(".yoyo.toml")];
    if let Some(p) = crate::cli::home_config_path() {
        paths.push(p);
    }
    if let Some(p) = crate::cli::user_config_path() {
        paths.push(p);
    }
    paths.iter().any(|p| {
        std::fs::read_to_string(p)
            .map(|c| config_content_has_api_key(&c))
            .unwrap_or(false)
    })
}

/// Is an API key reachable from the environment for this provider?
fn api_key_in_env(provider: &str) -> bool {
    let is_set = |var: &str| std::env::var(var).ok().filter(|k| !k.is_empty()).is_some();
    if let Some(env_var) = provider_api_key_env(provider) {
        if is_set(env_var) {
            return true;
        }
    }
    // Generic fallbacks, matching cli.rs's key resolution chain.
    is_set("ANTHROPIC_API_KEY") || is_set("API_KEY")
}

/// Check whether we should offer the setup wizard.
/// Thin wrapper: gather the facts, let `needs_setup_from` decide.
pub fn needs_setup(provider: &str) -> bool {
    needs_setup_from(
        provider,
        api_key_in_env(provider),
        api_key_in_config_files(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::KNOWN_PROVIDERS;
    use serial_test::serial;

    /// The decision matrix for "can yoyo actually start?" — one row per
    /// (provider, key_from_env, key_in_config) shape that reaches the wizard
    /// gate. The enumeration lives here in code, not in my memory.
    #[test]
    fn test_needs_setup_from_matrix() {
        // (provider, key_from_env, key_in_config, expected_needs_setup, why)
        let cases: &[(&str, bool, bool, bool, &str)] = &[
            // Local / self-hosted providers never need a key — never prompt them.
            ("ollama", false, false, false, "ollama needs no key"),
            (
                "custom",
                false,
                false,
                false,
                "custom base_url needs no key",
            ),
            (
                "ollama",
                true,
                false,
                false,
                "ollama with a key is still fine",
            ),
            // A reachable key means yoyo can start.
            ("anthropic", true, false, false, "key from env"),
            ("anthropic", false, true, false, "key from config file"),
            ("openai", true, true, false, "key from both sources"),
            // No reachable key: the wizard must offer itself. The presence of a
            // config file is irrelevant — a half-configured file (provider +
            // model, no key) used to lock the user out entirely (#628).
            (
                "anthropic",
                false,
                false,
                true,
                "keyless config must NOT lock out the wizard",
            ),
            ("openai", false, false, true, "no key anywhere, no config"),
            (
                "google",
                false,
                false,
                true,
                "unknown-to-env provider, no key",
            ),
        ];
        for (provider, env, cfg, expected, why) in cases {
            assert_eq!(
                needs_setup_from(provider, *env, *cfg),
                *expected,
                "provider={provider} env={env} config={cfg}: {why}"
            );
        }
    }

    #[test]
    fn test_config_content_has_api_key() {
        // The exact shape the wizard writes when the key is NOT saved: no key.
        assert!(!config_content_has_api_key(
            "provider = \"anthropic\"\nmodel = \"claude-opus-4-6\"\n"
        ));
        // Empty value is not a reachable key.
        assert!(!config_content_has_api_key("api_key = \"\"\n"));
        assert!(!config_content_has_api_key(""));
        // A real key is reachable.
        assert!(config_content_has_api_key(
            "provider = \"anthropic\"\napi_key = \"sk-ant-abc\"\n"
        ));
        // Commented-out keys don't count (parse_config_file skips comments).
        assert!(!config_content_has_api_key("# api_key = \"sk-ant-abc\"\n"));
    }

    #[test]
    fn test_parse_provider_choice_by_number() {
        assert_eq!(parse_provider_choice("1"), Some("anthropic"));
        assert_eq!(parse_provider_choice("2"), Some("openai"));
        assert_eq!(parse_provider_choice("3"), Some("google"));
        assert_eq!(parse_provider_choice("4"), Some("ollama"));
        assert_eq!(parse_provider_choice("5"), Some("openrouter"));
        assert_eq!(parse_provider_choice("6"), Some("deepseek"));
        assert_eq!(parse_provider_choice("7"), Some("groq"));
        assert_eq!(parse_provider_choice("8"), Some("xai"));
        assert_eq!(parse_provider_choice("9"), Some("mistral"));
        assert_eq!(parse_provider_choice("10"), Some("cerebras"));
        assert_eq!(parse_provider_choice("11"), Some("minimax"));
        assert_eq!(parse_provider_choice("12"), Some("bedrock"));
        assert_eq!(parse_provider_choice("13"), Some("github"));
        assert_eq!(parse_provider_choice("14"), Some("custom"));
    }

    #[test]
    fn test_parse_provider_choice_by_name() {
        assert_eq!(parse_provider_choice("anthropic"), Some("anthropic"));
        assert_eq!(parse_provider_choice("OpenAI"), Some("openai"));
        assert_eq!(parse_provider_choice("GOOGLE"), Some("google"));
        assert_eq!(parse_provider_choice("ollama"), Some("ollama"));
        assert_eq!(parse_provider_choice("cerebras"), Some("cerebras"));
        assert_eq!(parse_provider_choice("Cerebras"), Some("cerebras"));
        assert_eq!(parse_provider_choice("minimax"), Some("minimax"));
        assert_eq!(parse_provider_choice("MiniMax"), Some("minimax"));
        assert_eq!(parse_provider_choice("bedrock"), Some("bedrock"));
        assert_eq!(parse_provider_choice("Bedrock"), Some("bedrock"));
        assert_eq!(parse_provider_choice("github"), Some("github"));
        assert_eq!(parse_provider_choice("GitHub"), Some("github"));
        assert_eq!(parse_provider_choice("custom"), Some("custom"));
        assert_eq!(parse_provider_choice("CUSTOM"), Some("custom"));
    }

    #[test]
    fn test_parse_provider_choice_invalid() {
        assert_eq!(parse_provider_choice("0"), None);
        assert_eq!(parse_provider_choice("99"), None);
        assert_eq!(parse_provider_choice("banana"), None);
        assert_eq!(parse_provider_choice(""), None);
    }

    #[test]
    fn test_parse_provider_choice_whitespace() {
        assert_eq!(parse_provider_choice("  1  "), Some("anthropic"));
        assert_eq!(parse_provider_choice("  openai  "), Some("openai"));
    }

    #[test]
    fn test_generate_config_contents() {
        let config = generate_config_contents("anthropic", "claude-opus-4-6", None, None);
        assert!(config.contains("provider = \"anthropic\""));
        assert!(config.contains("model = \"claude-opus-4-6\""));
        assert!(config.starts_with("# yoyo configuration"));
        assert!(!config.contains("base_url"));
    }

    #[test]
    fn test_generate_config_openai() {
        let config = generate_config_contents("openai", "gpt-4o", None, None);
        assert!(config.contains("provider = \"openai\""));
        assert!(config.contains("model = \"gpt-4o\""));
    }

    #[test]
    fn test_generate_config_custom_with_base_url() {
        let config =
            generate_config_contents("custom", "my-model", Some("http://localhost:8080/v1"), None);
        assert!(config.contains("provider = \"custom\""));
        assert!(config.contains("model = \"my-model\""));
        assert!(config.contains("base_url = \"http://localhost:8080/v1\""));
    }

    #[test]
    fn test_wizard_providers_are_known() {
        for &(slug, _) in WIZARD_PROVIDERS {
            assert!(
                KNOWN_PROVIDERS.contains(&slug),
                "Wizard provider '{slug}' not in KNOWN_PROVIDERS"
            );
        }
    }

    #[test]
    fn test_wizard_anthropic_with_key() {
        // Simulate: choose anthropic (1), enter a key, accept default model, save=no
        let input = "1\nsk-test-key-123\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "anthropic");
        assert_eq!(r.api_key, "sk-test-key-123");
        assert_eq!(r.model, "claude-opus-4-6"); // default

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("Step 1"));
        assert!(output_str.contains("Step 2"));
        assert!(output_str.contains("Step 3"));
        assert!(output_str.contains("Step 4"));
        assert!(output_str.contains("All set!"));
    }

    #[test]
    fn test_wizard_ollama_skips_api_key() {
        // Choose ollama (4), pick default model, save=no
        let input = "4\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "ollama");
        assert_eq!(r.api_key, "not-needed");
        assert_eq!(r.model, "llama3.2"); // default for ollama

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("No API key needed"));
    }

    #[test]
    fn test_wizard_custom_model() {
        // Choose openai (2), enter key, type custom model, save=no
        let input = "2\nsk-openai-key\ngpt-4.1-mini\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "openai");
        assert_eq!(r.api_key, "sk-openai-key");
        assert_eq!(r.model, "gpt-4.1-mini");
    }

    #[test]
    fn test_wizard_provider_by_name() {
        // Type provider name instead of number
        let input = "google\ntest-key\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "google");
        assert_eq!(r.api_key, "test-key");
    }

    #[test]
    fn test_wizard_default_provider_on_enter() {
        // Just press enter for provider (defaults to anthropic), then enter key, etc.
        let input = "\nmy-api-key\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "anthropic");
        assert_eq!(r.api_key, "my-api-key");
    }

    #[test]
    fn test_wizard_no_key_no_env_returns_none() {
        // Choose anthropic, enter empty key with no env var set
        // We need to make sure the env var is not set for this test
        let input = "1\n\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        // Temporarily unset the env var if set
        let prev = std::env::var("ANTHROPIC_API_KEY").ok();
        std::env::remove_var("ANTHROPIC_API_KEY");

        let result = run_wizard_interactive(&mut reader, &mut output);

        // Restore
        if let Some(val) = prev {
            std::env::set_var("ANTHROPIC_API_KEY", val);
        }

        assert!(result.is_none());
        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("No API key provided"));
    }

    #[test]
    fn test_save_config_to_file() {
        // Use a temp dir to avoid polluting the project
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard")
            .tempdir()
            .unwrap();

        let result = save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None);
        assert!(result.is_ok());

        let content = std::fs::read_to_string(tmp_dir.path().join(".yoyo.toml")).unwrap();
        assert!(content.contains("provider = \"openai\""));
        assert!(content.contains("model = \"gpt-4o\""));
    }

    #[test]
    fn test_save_over_existing_creates_bak_with_original_contents() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_bak")
            .tempdir()
            .unwrap();
        let path = tmp_dir.path().join(".yoyo.toml");
        let original = "provider = \"anthropic\"\nmodel = \"old-model\"\nauto_watch = true\n";
        std::fs::write(&path, original).unwrap();

        let result = save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None);
        assert!(result.is_ok());

        let bak_path = tmp_dir.path().join(".yoyo.toml.bak");
        assert!(bak_path.exists(), ".bak should exist after overwrite");
        let bak_contents = std::fs::read_to_string(&bak_path).unwrap();
        assert_eq!(
            bak_contents, original,
            ".bak should hold the ORIGINAL contents"
        );
    }

    #[test]
    fn test_save_over_existing_preserves_unmanaged_keys() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_preserve")
            .tempdir()
            .unwrap();
        let path = tmp_dir.path().join(".yoyo.toml");
        std::fs::write(
            &path,
            "provider = \"anthropic\"\nmodel = \"old-model\"\nauto_watch = true\n",
        )
        .unwrap();

        save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(
            content.contains("auto_watch = true"),
            "unmanaged key should survive: {content}"
        );
        assert!(
            content.contains("# preserved from previous config"),
            "preserved keys should be under a comment: {content}"
        );
    }

    #[test]
    fn test_save_over_existing_managed_key_not_duplicated() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_managed")
            .tempdir()
            .unwrap();
        let path = tmp_dir.path().join(".yoyo.toml");
        std::fs::write(
            &path,
            "provider = \"anthropic\"\nmodel = \"old-model\"\nbase_url = \"http://old\"\n",
        )
        .unwrap();

        save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("model = \"gpt-4o\""), "new value wins");
        assert!(
            !content.contains("old-model"),
            "old managed value must not be duplicated: {content}"
        );
        assert!(
            !content.contains("http://old"),
            "old base_url is managed — must not be re-appended: {content}"
        );
        assert_eq!(
            content.matches("model = ").count(),
            1,
            "exactly one model key: {content}"
        );
    }

    #[test]
    fn test_fresh_save_creates_no_bak() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_fresh")
            .tempdir()
            .unwrap();

        save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None).unwrap();

        assert!(
            !tmp_dir.path().join(".yoyo.toml.bak").exists(),
            "fresh save must not create a .bak"
        );
        let content = std::fs::read_to_string(tmp_dir.path().join(".yoyo.toml")).unwrap();
        assert!(
            !content.contains("# preserved from previous config"),
            "fresh save must not include a preserved comment"
        );
    }

    #[test]
    fn test_save_over_existing_only_managed_keys_appends_nothing() {
        // Paired negative (Day 122 lesson): old file with ONLY managed keys →
        // no "# preserved" comment, nothing appended.
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_negative")
            .tempdir()
            .unwrap();
        let path = tmp_dir.path().join(".yoyo.toml");
        std::fs::write(&path, "provider = \"anthropic\"\nmodel = \"old-model\"\n").unwrap();

        save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(
            !content.contains("# preserved from previous config"),
            "no unmanaged keys → no preserved comment: {content}"
        );
        // .bak is still written — backup happens regardless of key preservation
        assert!(tmp_dir.path().join(".yoyo.toml.bak").exists());
    }

    #[test]
    fn test_save_over_existing_stops_scan_at_first_section() {
        // Keys inside [section] blocks are NOT top-level — must not be appended.
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_section")
            .tempdir()
            .unwrap();
        let path = tmp_dir.path().join(".yoyo.toml");
        std::fs::write(
            &path,
            "provider = \"anthropic\"\nauto_watch = true\n[permissions]\nallow_all = true\n",
        )
        .unwrap();

        save_config_to_file(tmp_dir.path(), "openai", "gpt-4o", None, None).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(
            content.contains("auto_watch = true"),
            "top-level unmanaged key survives: {content}"
        );
        assert!(
            !content.contains("allow_all"),
            "section keys must not be mis-appended as top-level: {content}"
        );
    }

    #[test]
    fn test_preserved_unmanaged_lines_skips_comments_and_blanks() {
        let old = "# a comment\n\nprovider = \"x\"\ncustom_key = 1\n";
        let preserved = preserved_unmanaged_lines(old);
        assert_eq!(preserved, vec!["custom_key = 1".to_string()]);
    }

    #[test]
    #[serial]
    fn test_save_config_to_user_file_backs_up_existing() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_xdg_bak")
            .tempdir()
            .unwrap();
        let prev_xdg = std::env::var("XDG_CONFIG_HOME").ok();
        std::env::set_var("XDG_CONFIG_HOME", tmp_dir.path());

        let config_path = tmp_dir.path().join("yoyo").join("config.toml");
        std::fs::create_dir_all(config_path.parent().unwrap()).unwrap();
        std::fs::write(&config_path, "provider = \"google\"\nauto_watch = true\n").unwrap();

        let result = save_config_to_user_file("openai", "gpt-4o", None, None);
        assert!(result.is_ok());

        let bak_path = tmp_dir.path().join("yoyo").join("config.toml.bak");
        assert!(bak_path.exists(), "user config backup should exist");
        let content = std::fs::read_to_string(&config_path).unwrap();
        assert!(
            content.contains("auto_watch = true"),
            "unmanaged key survives in user config: {content}"
        );

        if let Some(val) = prev_xdg {
            std::env::set_var("XDG_CONFIG_HOME", val);
        } else {
            std::env::remove_var("XDG_CONFIG_HOME");
        }
    }

    #[test]
    fn test_wizard_result_fields() {
        let result = WizardResult {
            provider: "anthropic".to_string(),
            api_key: "sk-test".to_string(),
            model: "claude-opus-4-6".to_string(),
            base_url: None,
        };
        assert_eq!(result.provider, "anthropic");
        assert_eq!(result.api_key, "sk-test");
        assert_eq!(result.model, "claude-opus-4-6");
        assert_eq!(result.base_url, None);
    }

    #[test]
    fn test_wizard_cerebras_flow() {
        // Choose cerebras (10), enter key, accept default model, save=no
        let input = "10\nsk-cerebras-key\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "cerebras");
        assert_eq!(r.api_key, "sk-cerebras-key");
        assert_eq!(r.model, "llama-3.3-70b"); // default for cerebras
        assert_eq!(r.base_url, None);

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("Cerebras"));
    }

    #[test]
    fn test_wizard_minimax_flow() {
        // Choose minimax (11), enter API key, accept default model, save=no
        let input = "11\nsk-minimax-key\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "minimax");
        assert_eq!(r.api_key, "sk-minimax-key");
        assert_eq!(r.model, "MiniMax-M2.7"); // default for minimax
        assert_eq!(r.base_url, None);

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("MiniMax"));
    }

    #[test]
    fn test_wizard_custom_provider_flow() {
        // Choose custom (14), enter API key, enter base URL, accept default model, save=no
        let input = "14\nmy-custom-key\nhttp://localhost:8080/v1\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "custom");
        assert_eq!(r.api_key, "my-custom-key");
        assert_eq!(r.base_url, Some("http://localhost:8080/v1".to_string()));

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("Base URL"));
        assert!(output_str.contains("Custom (self-hosted OpenAI-compatible)"));
    }

    #[test]
    fn test_wizard_custom_provider_no_base_url_returns_none() {
        // Choose custom (14), enter API key, enter empty base URL
        let input = "14\nmy-custom-key\n\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_none());

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("No base URL provided"));
    }

    #[test]
    fn test_parse_save_choice_defaults_to_project() {
        assert_eq!(parse_save_choice(""), SaveLocation::Project);
        assert_eq!(parse_save_choice("1"), SaveLocation::Project);
        assert_eq!(parse_save_choice("p"), SaveLocation::Project);
        assert_eq!(parse_save_choice("project"), SaveLocation::Project);
        assert_eq!(parse_save_choice("  1  "), SaveLocation::Project);
    }

    #[test]
    fn test_parse_save_choice_user() {
        assert_eq!(parse_save_choice("2"), SaveLocation::User);
        assert_eq!(parse_save_choice("u"), SaveLocation::User);
        assert_eq!(parse_save_choice("user"), SaveLocation::User);
        assert_eq!(parse_save_choice("global"), SaveLocation::User);
        assert_eq!(parse_save_choice("  2  "), SaveLocation::User);
    }

    #[test]
    fn test_parse_save_choice_skip() {
        assert_eq!(parse_save_choice("3"), SaveLocation::Skip);
        assert_eq!(parse_save_choice("n"), SaveLocation::Skip);
        assert_eq!(parse_save_choice("no"), SaveLocation::Skip);
        assert_eq!(parse_save_choice("none"), SaveLocation::Skip);
        assert_eq!(parse_save_choice("s"), SaveLocation::Skip);
        assert_eq!(parse_save_choice("skip"), SaveLocation::Skip);
    }

    #[test]
    fn test_parse_save_choice_unknown_defaults_to_project() {
        assert_eq!(parse_save_choice("banana"), SaveLocation::Project);
        assert_eq!(parse_save_choice("yes"), SaveLocation::Project);
    }

    #[test]
    #[serial]
    fn test_save_config_to_user_file() {
        // Use a temp dir to simulate XDG_CONFIG_HOME
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_xdg_save")
            .tempdir()
            .unwrap();

        // Override XDG_CONFIG_HOME so user_config_path() points here
        let prev_xdg = std::env::var("XDG_CONFIG_HOME").ok();
        std::env::set_var("XDG_CONFIG_HOME", tmp_dir.path());

        let result = save_config_to_user_file("google", "gemini-2.0-flash", None, None);
        assert!(result.is_ok(), "save_config_to_user_file should succeed");
        let path_str = result.unwrap();
        assert!(
            path_str.contains("yoyo"),
            "path should contain yoyo directory"
        );
        assert!(
            path_str.contains("config.toml"),
            "path should end with config.toml"
        );

        // Verify file contents
        let content = std::fs::read_to_string(&path_str).unwrap();
        assert!(content.contains("provider = \"google\""));
        assert!(content.contains("model = \"gemini-2.0-flash\""));

        // Cleanup env
        if let Some(val) = prev_xdg {
            std::env::set_var("XDG_CONFIG_HOME", val);
        } else {
            std::env::remove_var("XDG_CONFIG_HOME");
        }
    }

    #[test]
    #[serial]
    fn test_save_config_to_user_file_creates_parent_dirs() {
        // Use a temp dir with nested path to verify parent creation
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_xdg_nested")
            .tempdir()
            .unwrap();

        let prev_xdg = std::env::var("XDG_CONFIG_HOME").ok();
        std::env::set_var("XDG_CONFIG_HOME", tmp_dir.path());

        let result = save_config_to_user_file("openai", "gpt-4o", None, None);
        assert!(
            result.is_ok(),
            "should create parent dirs: {:?}",
            result.err()
        );

        let expected_path = tmp_dir.path().join("yoyo").join("config.toml");
        assert!(expected_path.exists(), "config file should exist");

        // Cleanup env
        if let Some(val) = prev_xdg {
            std::env::set_var("XDG_CONFIG_HOME", val);
        } else {
            std::env::remove_var("XDG_CONFIG_HOME");
        }
    }

    #[test]
    fn test_wizard_step4_shows_three_choices() {
        // Choose ollama (4), default model, then check Step 4 output shows 3 options
        let input = "4\n\n3\n"; // ollama, default model, skip saving
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());

        let output_str = String::from_utf8(output).unwrap();
        assert!(
            output_str.contains(".yoyo.toml"),
            "should show project-level option"
        );
        assert!(
            output_str.contains("user-level"),
            "should show user-level option"
        );
        assert!(output_str.contains("Don't save"), "should show skip option");
        assert!(
            output_str.contains("Choice [1]"),
            "should show choice prompt with default"
        );
    }

    #[test]
    #[serial]
    fn test_wizard_save_to_user_level() {
        // Set up a temp XDG dir so saving actually works
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_user_save")
            .tempdir()
            .unwrap();

        let prev_xdg = std::env::var("XDG_CONFIG_HOME").ok();
        std::env::set_var("XDG_CONFIG_HOME", tmp_dir.path());

        // Choose ollama (4), default model, save to user-level (2)
        let input = "4\n\n2\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());

        let output_str = String::from_utf8(output).unwrap();
        assert!(
            output_str.contains("Saved to"),
            "should confirm save: {output_str}"
        );

        // Verify file was actually created
        let expected_path = tmp_dir.path().join("yoyo").join("config.toml");
        assert!(
            expected_path.exists(),
            "user-level config should be created"
        );
        let content = std::fs::read_to_string(&expected_path).unwrap();
        assert!(content.contains("provider = \"ollama\""));

        // Cleanup env
        if let Some(val) = prev_xdg {
            std::env::set_var("XDG_CONFIG_HOME", val);
        } else {
            std::env::remove_var("XDG_CONFIG_HOME");
        }
    }

    #[test]
    fn test_user_config_display_path() {
        // Just verify the function returns something reasonable
        let display = user_config_display_path();
        assert!(
            display.contains("yoyo") || display.contains("config"),
            "display path should mention yoyo or config: {display}"
        );
    }

    #[test]
    fn test_bedrock_in_wizard_providers() {
        let slugs: Vec<&str> = WIZARD_PROVIDERS.iter().map(|&(s, _)| s).collect();
        assert!(
            slugs.contains(&"bedrock"),
            "bedrock should be in WIZARD_PROVIDERS"
        );
    }

    #[test]
    fn test_generate_config_bedrock() {
        let config = generate_config_contents(
            "bedrock",
            "anthropic.claude-sonnet-4-20250514-v1:0",
            Some("https://bedrock-runtime.us-east-1.amazonaws.com"),
            None,
        );
        assert!(config.contains("provider = \"bedrock\""));
        assert!(config.contains("model = \"anthropic.claude-sonnet-4-20250514-v1:0\""));
        assert!(config.contains("base_url = \"https://bedrock-runtime.us-east-1.amazonaws.com\""));
        assert!(config.contains("AWS_ACCESS_KEY_ID"));
        assert!(config.contains("AWS_SECRET_ACCESS_KEY"));
        // Verify it's valid-ish TOML (lines starting with # are comments, others are key=value)
        for line in config.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            assert!(
                trimmed.contains('='),
                "non-comment line should be key=value: {trimmed}"
            );
        }
    }

    #[test]
    fn test_wizard_bedrock_with_credentials() {
        // Choose bedrock (12), enter access key, secret key, default region, default model, save=no
        let input = "12\nAKIATEST123\nwJalrXUtnFEMI/test\n\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some(), "wizard should succeed for bedrock");
        let r = result.unwrap();
        assert_eq!(r.provider, "bedrock");
        assert_eq!(r.api_key, "AKIATEST123:wJalrXUtnFEMI/test");
        assert_eq!(r.model, "anthropic.claude-sonnet-4-6"); // default
        assert_eq!(
            r.base_url.as_deref(),
            Some("https://bedrock-runtime.us-east-1.amazonaws.com")
        );

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("AWS credentials received"));
        assert!(output_str.contains("us-east-1"));
    }

    // --- API key persistence (#628) ---

    #[test]
    fn test_generate_config_with_api_key_emits_line() {
        let config = generate_config_contents("minimax", "MiniMax-M2.7", None, Some("k"));
        assert!(
            config.contains("api_key = \"k\""),
            "key should be persisted: {config}"
        );
    }

    #[test]
    fn test_generate_config_without_api_key_emits_no_line() {
        let config = generate_config_contents("minimax", "MiniMax-M2.7", None, None);
        assert!(
            !config.contains("api_key"),
            "no key line when None: {config}"
        );
    }

    #[test]
    fn test_generate_config_empty_api_key_treated_as_absent() {
        let config = generate_config_contents("minimax", "MiniMax-M2.7", None, Some(""));
        assert!(!config.contains("api_key"), "empty key is absent: {config}");
        let config = generate_config_contents("minimax", "MiniMax-M2.7", None, Some("   "));
        assert!(
            !config.contains("api_key"),
            "whitespace-only key is absent: {config}"
        );
    }

    #[test]
    fn test_generate_config_escapes_quotes_in_key() {
        let config = generate_config_contents("custom", "m", None, Some("a\"b\\c"));
        assert!(
            config.contains("api_key = \"a\\\"b\\\\c\""),
            "quotes and backslashes escaped: {config}"
        );
    }

    #[test]
    fn test_resave_over_existing_api_key_yields_exactly_one() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_resave_key")
            .tempdir()
            .unwrap();
        std::fs::write(
            tmp_dir.path().join(".yoyo.toml"),
            "provider = \"minimax\"\napi_key = \"old-key\"\nauto_watch = true\n",
        )
        .unwrap();

        save_config_to_file(
            tmp_dir.path(),
            "minimax",
            "MiniMax-M2.7",
            None,
            Some("new-key"),
        )
        .unwrap();

        let content = std::fs::read_to_string(tmp_dir.path().join(".yoyo.toml")).unwrap();
        let count = content
            .lines()
            .filter(|l| l.trim_start().starts_with("api_key"))
            .count();
        assert_eq!(count, 1, "exactly one api_key line: {content}");
        assert!(content.contains("api_key = \"new-key\""));
        assert!(
            content.contains("auto_watch = true"),
            "unmanaged key still preserved: {content}"
        );
    }

    #[test]
    fn test_resave_without_key_drops_old_key_line_not_duplicated() {
        // api_key is a MANAGED key, so an old one is never re-appended as
        // "preserved from previous config".
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_resave_nokey")
            .tempdir()
            .unwrap();
        std::fs::write(
            tmp_dir.path().join(".yoyo.toml"),
            "provider = \"minimax\"\napi_key = \"old-key\"\n",
        )
        .unwrap();

        save_config_to_file(tmp_dir.path(), "minimax", "MiniMax-M2.7", None, None).unwrap();

        let content = std::fs::read_to_string(tmp_dir.path().join(".yoyo.toml")).unwrap();
        assert!(
            !content.contains("api_key"),
            "old key must not be resurrected into preserved block: {content}"
        );
    }

    #[test]
    fn test_key_is_savable() {
        assert!(key_is_savable("minimax", "sk-1"));
        assert!(key_is_savable("bedrock", "a:b"));
        assert!(!key_is_savable("ollama", "not-needed"));
        assert!(!key_is_savable("minimax", ""));
        assert!(!key_is_savable("minimax", "   "));
    }

    #[test]
    fn test_parse_yes_default_no() {
        assert!(parse_yes_default_no("y"));
        assert!(parse_yes_default_no("Y\n"));
        assert!(parse_yes_default_no(" yes "));
        assert!(!parse_yes_default_no(""));
        assert!(!parse_yes_default_no("\n"));
        assert!(!parse_yes_default_no("n"));
        assert!(!parse_yes_default_no("banana"));
    }

    #[test]
    fn test_key_not_saved_notice_names_env_var() {
        let notice = key_not_saved_notice("minimax", Some("/tmp/config.toml"));
        assert!(notice.contains("MINIMAX_API_KEY"), "{notice}");
        assert!(notice.contains("/tmp/config.toml"), "{notice}");
        assert!(notice.contains("not saved"), "{notice}");
    }

    #[test]
    fn test_key_not_saved_notice_bedrock_names_both_vars() {
        let notice = key_not_saved_notice("bedrock", None);
        assert!(notice.contains("AWS_ACCESS_KEY_ID"), "{notice}");
        assert!(notice.contains("AWS_SECRET_ACCESS_KEY"), "{notice}");
    }

    #[test]
    fn test_wizard_saves_key_when_confirmed() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_key_yes")
            .tempdir()
            .unwrap();
        let prev_cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(tmp_dir.path()).unwrap();

        // minimax (11), key, default model, save to project (1), save key = y
        let input = "11\nsk-minimax-secret\n\n1\ny\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();
        let result = run_wizard_interactive(&mut reader, &mut output);

        let content = std::fs::read_to_string(tmp_dir.path().join(".yoyo.toml")).ok();
        std::env::set_current_dir(prev_cwd).unwrap();

        assert!(result.is_some());
        let content = content.expect("config should have been written");
        assert!(
            content.contains("api_key = \"sk-minimax-secret\""),
            "key should be persisted: {content}"
        );

        let output_str = String::from_utf8(output).unwrap();
        assert!(
            output_str.contains("Save the API key to this file?"),
            "should ask before writing a secret: {output_str}"
        );
    }

    #[test]
    fn test_wizard_declines_key_and_prints_export_instructions() {
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_wizard_key_no")
            .tempdir()
            .unwrap();
        let prev_cwd = std::env::current_dir().unwrap();
        std::env::set_current_dir(tmp_dir.path()).unwrap();

        // minimax (11), key, default model, save to project (1), save key = n
        let input = "11\nsk-minimax-secret\n\n1\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();
        let result = run_wizard_interactive(&mut reader, &mut output);

        let content = std::fs::read_to_string(tmp_dir.path().join(".yoyo.toml")).ok();
        std::env::set_current_dir(prev_cwd).unwrap();

        assert!(result.is_some());
        let content = content.expect("config should have been written");
        assert!(
            !content.contains("api_key"),
            "key must NOT be written when declined: {content}"
        );

        let output_str = String::from_utf8(output).unwrap();
        assert!(
            output_str.contains("MINIMAX_API_KEY"),
            "must tell the user how to supply the key: {output_str}"
        );
        assert!(output_str.contains("not saved"), "{output_str}");
    }

    #[test]
    fn test_wizard_skip_save_still_explains_key_route() {
        // minimax (11), key, default model, don't save (3) — no file, so no prompt,
        // but the user must still learn where to put the key.
        let input = "11\nsk-minimax-secret\n\n3\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();
        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());

        let output_str = String::from_utf8(output).unwrap();
        assert!(
            !output_str.contains("Save the API key to this file?"),
            "no file is written — don't ask: {output_str}"
        );
        assert!(
            output_str.contains("MINIMAX_API_KEY"),
            "must explain the env-var route: {output_str}"
        );
    }

    #[test]
    #[cfg(unix)]
    fn test_saved_config_with_key_is_owner_only() {
        use std::os::unix::fs::PermissionsExt;
        let tmp_dir = tempfile::Builder::new()
            .prefix("yoyo_test_key_perms")
            .tempdir()
            .unwrap();
        save_config_to_file(
            tmp_dir.path(),
            "minimax",
            "MiniMax-M2.7",
            None,
            Some("sk-x"),
        )
        .unwrap();
        let mode = std::fs::metadata(tmp_dir.path().join(".yoyo.toml"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "config with a secret must be 0600");
    }

    #[test]
    fn test_wizard_bedrock_custom_region() {
        // Choose bedrock (12), enter credentials, custom region, default model, save=no
        let input = "12\nAKIATEST123\nsecretkey\neu-west-1\n\nn\n";
        let mut reader = io::Cursor::new(input.as_bytes());
        let mut output = Vec::new();

        let result = run_wizard_interactive(&mut reader, &mut output);
        assert!(result.is_some());
        let r = result.unwrap();
        assert_eq!(r.provider, "bedrock");
        assert_eq!(
            r.base_url.as_deref(),
            Some("https://bedrock-runtime.eu-west-1.amazonaws.com")
        );

        let output_str = String::from_utf8(output).unwrap();
        assert!(output_str.contains("eu-west-1"));
    }
}
